# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hive

 pod 'Alamofire'
 pod 'IBAnimatable'
 pod 'RxCocoa'
 pod 'RxSwift'
 pod 'IQKeyboardManagerSwift'
 pod 'SideMenuController'
 pod 'Firebase/Database'
 pod 'Firebase/Auth'
 pod 'Firebase/Storage'
 pod 'MBProgressHUD'
 pod 'Nuke'

#pod 'Firebase/Core'
pod 'Firebase/Messaging'

end
